### ISSUE TITLE
About Reproduction of the numbers in the paper!

### ISSUE THREAD

**Issue by Z-Z-J** [ZhimingZo/Modulated-GCN#1]
![QQ截图20211019142826](https://user-images.githubusercontent.com/53818279/137855486-6eb41daa-72a6-48ee-99bf-8e6ca1b92cb8.png)
This is my training result: 52.73.
The result given in Table 5 in your paper is 49.4.
I don't know how to solve this problem, I hope you can help me solve this problem.

**Comment by ZhimingZo** [comment]
Hi, thanks for your question. 
First, you may want to try different random seeds (Sorry, I did not record the exact random seed for the best model before refinement network (50.73mm) ). I tried to set it to 1 and obtained a result 51.28 mm MPJPE a few days ago.  
Second, there are two stages, you may want to use the refinement network to further boost the performance.

**Comment by SuperAttitude** [comment]
Hello, I see that you output the error of each action. I'm doing similar work, but I don't know how to get the error value of each action. Can you help me？

**Comment by Z-Z-J** [comment]
> 您好，我看到您输出每个操作的错误。我正在做类似的工作，但我不知道如何获取每个操作的错误值。你可以帮我吗？
First experiment (Modulated-GCN_benchmark),  The code provided by the author contains how to get the error value of each action .

**Comment by SuperAttitude** [comment]
> > 您好，我看到您输出每个操作的错误。我正在做类似的工作，但我不知道如何获取每个操作的错误值。你可以帮我吗？
> > First experiment (Modulated-GCN_benchmark),  The code provided by the author contains how to get the error value of each action .

Thank you for your quick reply. Thank you very much. I'll study the first experiment

**Comment by Z-Z-J** [comment]
> 您好，我看到您输出每个操作的错误。我正在做类似的工作，但我不知道如何获取每个操作的错误值。你可以帮我吗？
First experiment ()

**Comment by jianlai123-123** [comment]
Hello, may I ask you some questions? First, do you need to prepare the human 3.6 dataset yourself? Where is the dataset directory? Second, what if gdown -- id 1P7W3ldx2lxaYJYcf3RG4Y9PsD4EJ6b0 cannot be opened? Third, does the data you run show the same effect as Table 5?
Looking forward to your reply, thank you! @Z-Z-J
