### ISSUE TITLE
h36m_skeleton_joints_group

### ISSUE THREAD

**Issue by qihao067** [ZhimingZo/Modulated-GCN#2]
Hi! Thanks for your work.

I am trying to use your work on other datasets and am confused about the definition of 'h36m_skeleton_joints_group'.

`h36m_skeleton_joints_group = [[2, 3], [5, 6], [1, 4], [0, 7], [8, 9], [14, 15], [11, 12], [10, [13]]`

For example, 5 is r-top and 6 is l-hip... Why do you group these two joints? How can I define the 'h36m_skeleton_joints_group' on other dataset? Thank you!!

**Comment by ZhimingZo** [comment]
Hi, we did not actually use the joints group, for more details about joints groups, you can refer to the Semantic GCN Github.
Thank you
