### ISSUE TITLE
Performance 

### ISSUE THREAD

**Issue by fighting-mumu** [ZhimingZo/Modulated-GCN#4]
Thanks for your novelty work, I retrain the network, but I can only get  51.33 on average MPJPE, which is lower than your paper's performance of 49.4.  You use the refinement module, if it is not fair that other methods don't use the refinement module?

**Comment by Z-Z-J** [comment]
> Thanks for your novelty work, I retrain the network, but I can only get 51.33 on average MPJPE, which is lower than your paper's performance of 49.4. You use the refinement module, if it is not fair that other methods don't use the refinement module?

I also noticed this problem, but I think
First,  when GT is used as  input data, all work should be compared fairly.
Second, when 2D detector results is used as input data, all work will report the best performance.
