### ISSUE TITLE
Testing on MPI-INF-3DHP

### ISSUE THREAD

**Issue by nies14** [ZhimingZo/Modulated-GCN#5]
Thanks for the great work. Could you please tell me how can I test on the MPI-INF-3DHP dataset & reproduce the result of Table 7?

**Comment by nies14** [comment]
I have prepared the 2d inputs from VideoPose3d (https://github.com/facebookresearch/VideoPose3D/blob/main/DATASETS.md). But getting the following error.
"RuntimeError: shape '[256, -1, 17, 3]' is invalid for input of size 12288"

**Comment by jianlai123-123** [comment]
Hello, have you resolved this issue? How to obtain the dataset MPI-INF-3DHP. Do I need to process it after obtaining it? Under which data file? How to run the code? Looking forward to your reply, thank you! @nies14

**Comment by nies14** [comment]
> Hello, have you resolved this issue? How to obtain the dataset MPI-INF-3DHP. Do I need to process it after obtaining it? Under which data file? How to run the code? Looking forward to your reply, thank you! @nies14

Hi,
You can follow this repo [MLP-Graph](https://github.com/nies14/Spatio-Temporal-MLP-Graph)
